### ISSUE TITLE
Teeworlds license

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds-go/huffman#1]
This package appears to be a one-to-one translation of https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/src/engine/shared/huffman.cpp and https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/src/engine/shared/huffman.h. As such, the original license still applies. Could you add that to the license text?

**Comment by ChillerDragon** [comment]
Isn't rewrite in another language always license dodge? Anyways I am not a lawyer I am not sure what I should do now. Could you pr a new license file then I will merge it. Otherwise I don't think me doing a random thing is any good.

**Comment by heinrich5991** [comment]
> Isn't rewrite in another language always license dodge?

No. A clean-room implementation is. Copying the source code retains the license.

> Could you pr a new license file then I will merge it. Otherwise I don't think me doing a random thing is any good.

I'll try.
